proxy:
  image: nginx:1.9
  volumes:
    - ./proxy:/etc/nginx/conf.d:ro
  volumes_from:
    - back
  ports:
    - '127.0.0.1:8080:80'
    - '127.0.0.1:8443:443'
  links:
    - front
    - back

front:
  image: befair/gasistafelice-front:latest
  volumes:
    - ./ui:/code/ui:rw

back:
  image: befair/gasistafelice-back:latest
  volumes:
    - ./gasistafelice:/code/gasistafelice:ro
  links:
    - db
  env_file: ./settings.env

db:
  image: postgres:9.4
  environment:
    POSTGRES_USER:     app
    POSTGRES_PASSWORD: app

hub:
  image: selenium/hub:latest

firefox:
  image: selenium/node-firefox:latest
  links:
    - hub
    - proxy

chrome:
  image: selenium/node-chrome:latest
  links:
    - hub
    - proxy

e2e:
  image: michelesr/protractor:latest
  volumes:
    - ./test/e2e:/code:ro
  links:
    - hub
