proxy:
  image: nginx:1.9
  volumes:
    - ./proxy:/etc/nginx/conf.d:ro
  volumes_from:
    - back
  ports:
    - '127.0.0.1:8080:80'
    - '127.0.0.1:8443:443'
  links:
    - front
    - back

front:
  image: befair/gasistafelice-front:latest
  volumes:
    - ./ui:/code/ui:rw

back:
  image: befair/gasistafelice-back:latest
  volumes:
    - ./gasistafelice:/code/gasistafelice:ro
    - ./gasistafelice/fixtures:/code/gasistafelice/fixtures:rw
    - /tmp/gf_tracebacker:/tmp/tracebacker:rw
  links:
    - db
  env_file: ./settings.env

db:
  image: postgres:9.4
  env_file: ./settings.env

hub:
  image: selenium/hub:latest

firefox:
  image: selenium/node-firefox-debug:latest
  links:
    - hub
    - proxy
  ports:
    - '127.0.0.1:5900:5900'

chrome:
  image: selenium/node-chrome-debug:latest
  links:
    - hub
    - proxy
  ports:
    - '127.0.0.1:5901:5900'

e2e:
  image: michelesr/protractor:latest
  volumes:
    - ./test/e2e:/code:ro
  links:
    - hub
