[uwsgi]
socket = 0.0.0.0:10013
protocol = uwsgi
# DEBUG http-socket = 0.0.0.0:10013
# DEBUG protocol = http
# KO docker does log-date = true
disable-logging = false
# logto = /app/uwsgi.log

# Defaults
autoload = false
master = true
no-orphans = true
enable-threads = true
buffer-size = 65536
auto-procname = true
thunder-lock = true
vacuum = true

# App specific
chdir = /app/gasistafelice

procname-prefix-spaced = gf_desmc_prod:
workers = 8
threads = 1
touch-chain-reload = /app/uwsgi.ini

max-requests = 128
harakiri = 6000
harakiri-verbose = true

master-fifo = /tmp/gf_desmc_prod.fifo
stats = 127.0.0.1:11013
#memory-report = true
enable-metrics = true
metrics-dir = /app/metrics
metrics-dir-restore = true

lazy-apps = true

wsgi-file = /app/gasistafelice/wsgi.py
env = DJANGO_SETTINGS_MODULE=gasistafelice.settings

plugin = python
pythonpath = /usr/local/lib/python2.7/
pythonpath = /usr/local/lib/python2.7/dist-packages
pythonpath = /usr/local/lib/python2.7/site-packages
pythonpath = /usr/local/lib/python2.7/lib-dynload/
pythonpath = /pysrc/
pythonpath = /app/
env = DJHISTORY_HOME=/usr/src/django-pro-history

