## role-related constants
NOBODY = 'NOBODY'
GAS_MEMBER = 'GAS_MEMBER'
GAS_REFERRER = 'GAS_REFERRER'
GAS_REFERRER_SUPPLIER = 'GAS_REFERRER_SUPPLIER'
GAS_REFERRER_ORDER = 'GAS_REFERRER_ORDER'
GAS_REFERRER_WITHDRAWAL = 'GAS_REFERRER_WITHDRAWAL'
GAS_REFERRER_DELIVERY = 'GAS_REFERRER_DELIVERY'
GAS_REFERRER_CASH = 'GAS_REFERRER_CASH'
GAS_REFERRER_TECH = 'GAS_REFERRER_TECH'
SUPPLIER_REFERRER = 'SUPPLIER_REFERRER'
DES_ADMIN = 'DES_ADMIN'

## QUESTION: Does the section below is useful/needed by some pieces of code in *Gasista Felice* ?

## permission-related constants
VIEW = 'view'
LIST = 'list'
CREATE = 'create'
EDIT = 'edit'
DELETE = 'delete'
ALL = 'all' # catchall
EDIT_MULTIPLE = 'edit_multiple'
CONFIRM = 'confirm'

## accounting-related constants
# account types
INCOME = 'INCOME'
EXPENSE = 'EXPENSE'
ASSET = 'ASSET'
LIABILITY = 'LIABILITY'
EQUITY = 'EQUITY'

# transaction types
INVOICE_PAYMENT = 'INVOICE_PAYMENT'
INVOICE_COLLECTION = 'INVOICE_COLLECTION'
GAS_MEMBER_RECHARGE = 'GAS_MEMBER_RECHARGE'
MEMBERSHIP_FEE_PAYMENT = 'MEMBERSHIP_FEE_PAYMENT' 

# group of Flexi-auth PrincipalParamRoleRelation
GROUP_INFORMATICS = 1 #"techs"
GROUP_SUPPLIERS = 2 #"suppliers"
GROUP_USERS = 3 #"users"
GROUP_MEMBERS = 4 #"gas"
GROUP_ECONOMICS = 5 #"economics"

