"""Models related to Order management (including state machine)."""

from django.db import models
from django.utils.translation import ugettext as ug, ugettext_lazy as _
from django.contrib.auth.models import User

from workflows.models import Workflow, Transition
from gasistafelice.base.workflows_utils import get_workflow, set_workflow, get_state, do_transition, get_allowed_transitions
from history.models import HistoricalRecords

from gasistafelice.base.models import PermissionResource, Place, DefaultTransition

from gasistafelice.lib.fields.models import CurrencyField, PrettyDecimalField
from gasistafelice.lib.fields import display
from gasistafelice.lib import ClassProperty
from gasistafelice.supplier.models import Supplier
from gasistafelice.gas.models.base import GASMember, GASSupplierSolidalPact, GASSupplierStock
from gasistafelice.gas.managers import AppointmentManager, OrderManager
from gasistafelice.gas import signals
from gasistafelice.base.models import Person
from gasistafelice.consts import *
from gasistafelice.gas.workflow_data import STATUS_PREPARED, STATUS_OPEN
from gasistafelice.gas.workflow_data import STATUS_CLOSED, STATUS_UNPAID
from gasistafelice.gas.workflow_data import STATUS_ARCHIVED, STATUS_CANCELED

from gasistafelice.gas.workflow_data import TRANSITION_OPEN, TRANSITION_CLOSE, TRANSITION_CLOSE_EMAIL
from gasistafelice.gas.workflow_data import TRANSITION_ARCHIVE, TRANSITION_UNPAID, TRANSITION_CANCEL


from gasistafelice.utils import long_date, medium_date

from flexi_auth.models import ParamRole
from flexi_auth.utils import register_parametric_role
from flexi_auth.exceptions import WrongPermissionCheck

from django.conf import settings

from workflows.utils import do_transition
from datetime import datetime, timedelta
import logging

log = logging.getLogger(__name__)

#from django.utils.encoding import force_unicode
import logging
log = logging.getLogger(__name__)

trans_state_d = {
    'Open' : 'Aperto',
    'Close': 'Chiuso',
    'Archived' : 'Archiviato',
    'Prepared' : 'Preparato',
    'Unpaid' : 'Insoluto',
    'Canceled' : 'Annullato',
}

OF = _('of')

class GASSupplierOrder(models.Model, PermissionResource):
    """An order issued by a GAS to a Supplier.
    See `here <http://www.jagom.org/trac/REESGas/wiki/BozzaVocabolario#OrdineFornitore>`__ for details (ITA only).

    * current_state is a meaningful parameter for order status from workflow system
    * gasstock_set references specified products available for the specific order \
      (they can be a subset of all available products from that Supplier for the order);

    """
    
    pact = models.ForeignKey(GASSupplierSolidalPact, related_name="order_set",verbose_name=_('pact'))
    datetime_start = models.DateTimeField(verbose_name=_('Date open'), default=datetime.now, help_text=_("when the order will be opened"))
    datetime_end = models.DateTimeField(verbose_name=_('Date close'), help_text=_("when the order will be closed"), null=True, blank=True)
    # minimum economic amount for the GASSupplierOrder to be accepted by the Supplier  
    order_minimum_amount = CurrencyField(verbose_name=_('Minimum amount'), null=True, blank=True)
    # Where and when Delivery occurs
    delivery = models.ForeignKey('Delivery', verbose_name=_('Delivery'), related_name="order_set", null=True, blank=True)
    # Where and when Withdrawal occurs
    withdrawal = models.ForeignKey('Withdrawal', verbose_name=_('Withdrawal'), related_name="order_set", null=True, blank=True)

    # Delivery cost. To be set after delivery has happened
    delivery_cost = CurrencyField(verbose_name=_('Delivery cost'), null=True, blank=True)

    gasstock_set = models.ManyToManyField(GASSupplierStock, verbose_name=_('GAS supplier stock'), help_text=_("products available for the order"), blank=True, through='GASSupplierOrderProduct')

    referrer_person = models.ForeignKey(Person, null=True, blank=True, related_name="order_set", verbose_name=_("order referrer"))
    delivery_referrer_person = models.ForeignKey(Person, null=True, related_name="delivery_for_order_set", blank=True, verbose_name=_("delivery referrer"))
    withdrawal_referrer_person = models.ForeignKey(Person, null=True, related_name="withdrawal_for_order_set", blank=True, verbose_name=_("withdrawal referrer"))

    group_id = models.PositiveIntegerField(verbose_name=_('Order group'), null=True, blank=True, 
        help_text=_("If not null this order is aggregate with orders from other GAS")
    )

    invoice_amount = CurrencyField(null=True, blank=True, verbose_name=_("invoice amount")) 
    invoice_note = models.TextField(blank=True, verbose_name=_("invoice number")) 

    root_plan = models.ForeignKey('GASSupplierOrder', null=True, default=None,
        help_text=_("Order was generated by another order"), verbose_name=_("planned order"))

    objects = OrderManager()

    history = HistoricalRecords()

    class Meta:
        verbose_name = _('order issued to supplier')
        verbose_name = _('orders issued to supplier')
        ordering = ('datetime_end', 'datetime_start')
        app_label = 'gas'
        
    def __init__(self, *args, **kw):
        super(GASSupplierOrder, self).__init__(*args, **kw)

    def __unicode__(self):

        d = {}

        d['date_start'] = medium_date(self.datetime_start)

        if self.datetime_end is not None:
            d['date_end'] = medium_date(self.datetime_end)
        d['date_delivery'] = ""
        if self.delivery:
            if self.delivery.date:
                d['date_delivery'] = medium_date(self.delivery.date)

        state = ""
        date_info = ""
        if self.current_state:
            state = self.current_state.name
            date_info = "("
            if state == STATUS_PREPARED:
                date_info += ug("apertura: %(date_start)s")
                if self.datetime_end:
                    date_info += ug(" - chiusura: %(date_end)s")
    
            elif state == STATUS_OPEN:
                if self.datetime_end:
                    date_info += ug("chiusura: %(date_end)s")

#                if d['date_delivery']:
#                    date_info += ug(" --> Deliver: %(date_delivery)s")
    
            elif state == STATUS_CLOSED:
#                if self.datetime_end:
#                    date_info += ug("Closed: %(date_end)s")

                if d['date_delivery']:
                    date_info += ug(" --> in consegna: %(date_delivery)s  --> to pay")

    
            elif state == STATUS_UNPAID:
                if d['date_delivery']:
                    date_info += ug(" --> consegnato: %(date_delivery)s --> to pay")

            elif state == STATUS_ARCHIVED:
                if d['date_delivery']:
                    date_info += ug("archiviato: %(date_delivery)s")
    
            elif state == STATUS_CANCELED:
                if d['date_delivery']:
                    date_info += ug("annullato: %(date_delivery)s")

            else:
                date_info += "TODO ?(%s)" % state
            date_info += ")"

        date_info = date_info % d

        state = trans_state_d.get(state, state)
        state += " " + date_info
        ref = self.referrer_person

        if ref:
            ref = " ref: %s " % ref
        elif self.referrer_person:
            ref = " ref: %s " % self.referrer_person
        else:
            ref = ""

        rv = _("Ord. %(order_num)s %(pact)s - %(state)s") % {
                    'pact' : self.pact,
                    'state' : state,
                    'order_num' : self.pk,
                    'ref' : ref
        }

        if self.group_id:
            rv += " --> InterGAS. %s" % (self.group_id)
        #if settings.DEBUG:
        #    rv += " [%s]" % self.pk
        return rv

    @property
    def report_name(self):
        log.debug("report_namereport_namereport_namereport_namereport_name")
        rep_date = medium_date(self.datetime_end)
        if self.delivery:
            if self.delivery.date:
                rep_date = medium_date(self.delivery.date)
        return u"Ord.%s %s %s %s" % (self.pk, OF, rep_date, self.supplier.subject_name)

    def do_transition(self, transition, user):
        super(GASSupplierOrder, self).do_transition(transition, user)
        signals.order_state_update.send(sender=self, transition=transition)

    def open_if_needed(self):
        """Check datetime_start and open order if needed."""
        log.debug("open_if_neededopen_if_neededopen_if_neededopen_if_neededopen_if_needed")
        if self.datetime_start <= datetime.now():

            # Act as superuser
            user = User.objects.get(username=settings.INIT_OPTIONS['su_username'])
            t_name = TRANSITION_OPEN
            t = Transition.objects.get(name__iexact=t_name, workflow=self.workflow)

            if t in get_allowed_transitions(self, user):
                log.debug("Do %s transition. datetime_start is %s" % (t, self.datetime_start))

                #20111212 02:00 prepare reccurent plan for order
                #FIXME: not done when using manual opening. Do it using worflow change state handler
                #WAS: self.set_default_gasstock_set()

                self.do_transition(t, user)


    def close_if_needed(self):
        """Check for datetime_end and close order if needed."""

        if self.datetime_end:
            if self.datetime_end <= datetime.now():

                # Act as superuser
                user = User.objects.get(username=settings.INIT_OPTIONS['su_username'])
                t_name = TRANSITION_CLOSE
                t = Transition.objects.get(name__iexact=t_name, workflow=self.workflow)

                log.debug("transitions %s. datetime_end is %s" % (get_allowed_transitions(self, user), self.datetime_end))
                if t in get_allowed_transitions(self, user):
                    log.debug("Do %s transition. datetime_end is %s" % (t, self.datetime_end))
                    self.do_transition(t, user)

    def get_valid_name(self):
        from django.template.defaultfilters import slugify
        from django.utils.encoding import smart_str
        n = str(self.pk) + '_'
        n += smart_str(slugify(self.pact.supplier.name).replace('-', '_'))
        #n += '_{0:%Y%m%d}'.format(self.delivery.date)
        #TODO: Auto create appointment for delivery date (Discuss about order type implementation)
        if self.delivery and self.delivery.date:
            n += '_{0:%Y%m%d}'.format(self.delivery.date)
        else:
            n += '_{0:%Y%m%d}'.format(datetime.now())
        return n
        #return self.pact.supplier.name.replace('-', '_').replace(' ', '_')

    #-- Contacts --#

    @property
    def contacts(self):
        return Contact.objects.filter(person__in=self.info_people)

    @property
    def info_people(self):
        return self.pact.info_people

    #-------------------------------------------------------------------------------#
    # Model Archive API

    def is_prepared(self):
        """
        Return `True` if the GAS supplier order is prepared; `False` otherwise.
        """
        #return self in GASSupplierOrder.objects.prepared()
        return self.current_state.name == STATUS_PREPARED

    def is_active(self):
        """
        Return `True` if the GAS supplier order is to be considered as 'active'; `False` otherwise.
        """
        #return self in GASSupplierOrder.objects.open()
        return self.current_state.name == STATUS_OPEN

    def is_archived(self):
        """
        Return `True` if the GAS supplier order is to be considered as 'archived'; `False` otherwise.
        """
        #return not self.is_active()
        return self.current_state.name == STATUS_ARCHIVED

    def is_closed(self):
        """
        Return `True` if the GAS supplier order is closed; `False` otherwise.
        """
        return self.current_state.name == STATUS_CLOSED

    def is_unpaid(self):
        """
        Return `True` if the GAS supplier order is closed but producer is not payed; `False` otherwise.
        """
        return self.current_state.name == STATUS_UNPAID

    def is_canceled(self):
        """
        Return `True` if the GAS supplier order is canceled; `False` otherwise.
        """
        return self.current_state.name == STATUS_CANCELED


    #-------------------------------------------------------------------------------#    

    @property
    def referrers(self):
        """Return all users being referrers for this order.

        Thus, referrer for order pact, if not take all gas referrers
        GAS teorie doesn't accept that one person is referrer for one person 
        but intend to turn the referrer work bettwen several persons.
        In the GAS you have one communicative referrer in order to centralize information
        """
        pact_refs = self.pact.referrers
        if not pact_refs:
            pact_refs = self.pact.gas.referrers

        #FIXME: 'NoneType' object has no attribute 'user'. Cannot be real. But model permitted
        if self.referrer_person:
            pact_refs |= User.objects.filter(pk=self.referrer_person.user.pk)
        return pact_refs

    @property
    def supplier_referrers_people(self):
        prs = Person.objects.none()
        if self.referrers:
            prs = Person.objects.filter(user__in=self.referrers)
        return prs

    @property
    def cash_referrers(self):
        return self.pact.gas.cash_referrers

    #-------------------------------------------------------------------------------#

    def set_default_gasstock_set(self):
        '''
        A helper function associating a default set of products to a GASSupplierOrder.
        
        At this time of execution we cannot use self.gasstock_set because we are building it.

        At this time of the software development every Product bound to pact,
        and so to the GAS, are included in list of orderable products for this order. 

        In future, we could have the ability to choice products one-by-one, but this is not
        our case now, so don't care about it.        
        '''

#COMMENT LF - TO BE REMOVED
#        if not self.pact.gas.config.auto_populate_products:
#            log.debug(ug("GAS is not configured to auto populate all products. You have to select every product you want to put into the order"))
#            return

        gasstocks = GASSupplierStock.objects.filter(pact=self.pact, enabled=True)
        if gasstocks and gasstocks.count() > 0:
            log.debug("Opening OOOOORDERRRRRR set_default_gasstock_set count: %s " % gasstocks.count())
        else:
            log.debug("Opening OOOOORDERRRRRR set_default_gasstock_set ?????? %s " % gasstocks)
        for s in gasstocks:
            #maybe works the more intuitive...self.orderable_product_set.add( ???
            GASSupplierOrderProduct.objects.create(order=self, 
                gasstock=s, initial_price=s.price, order_price=s.price, 
                delivered_price=s.price
            )

    def add_product(self, s):
        '''
        A helper function to add product to a GASSupplierOrder.
        '''

        # We can retrieve GASSupplierOrderProduct bound to this order with
        # self.orderable_products but it is useful to use get_or_create
        log.debug("GSOP add (%s) price(%s)" % (s, s.price))
        gsop, created = GASSupplierOrderProduct.objects.get_or_create(order=self, gasstock=s, order_price=s.price, initial_price=s.price)
        if created:
            log.debug('No GSOP found in order(%s) state(%s)' % (self.pk, self.current_state))
            gsop.order_price = s.price
            gsop.save()
        else:
            log.debug('GSOP already present in order(%s) state(%s)' % (self.pk, self.current_state))
            if gsop.delivered_price != s.price:
                gsop.delivered_price = s.price
                gsop.save()

    def remove_product(self, s):
        '''
        A helper function to remove a product from a GASSupplierOrder.
        '''
        #TODO: Does workflows.utils have method state_in(tupple of state)
        #if (order.current_state == OPEN) | (order.current_state == CLOSED) 

        try:
            gsop = self.orderable_products.get(gasstock=s)
            log.debug('product %s found in order %s' % (s.stock, self.order))
        except GASSupplierOrderProduct.DoesNotExist:
            log.debug('No product found in order(%s) state(%s)' % (self.pk, self.current_state))

        else:
            log.debug('product found in order(%s) state(%s)' % (self.pk, self.current_state))
            #Delete all GASMemberOrders done
            lst = gsop.gasmember_order_set.all()
            total = 0
            count = lst.count()
            for gmo in lst:
                total += gmo.ordered_price
                log.debug(ug('Deleting gas member %s email %s: Unit price(%s) ordered quantity(%s) total price(%s) for product %s') % (gmo.purchaser, gmo.purchaser.email, gmo.ordered_price, gmo.ordered_amount, gmo.ordered_price, gmo.product, ))
                signals.gmo_product_erased.send(sender=gmo)
                gmo.delete()
            log.debug('Deleted gas members orders (%s) for total of %s euro' % (count, total))
            gsop.delete()


    # Workflow management

    @property
    def current_state(self):
        return get_state(self)

    @property
    def workflow(self):
        return get_workflow(self)

    @workflow.setter
    def workflow(self, value=None):
        raise AttributeError(_("Workflow for specific GASSupplierOrder is not allowed. Just provide a default order workflow for your GAS"))

    def forward(self, user):
        """Apply default transition"""
        state = get_state(self)
        transition = DefaultTransition.objects.get(workflow=self.workflow, state=state).transition
        do_transition(self, transition, user)
 
    # -- Resource API --#

    @ClassProperty
    @classmethod
    def resource_type(cls):
        return "order"
    
    @property
    def parent(self):
        return self.pact

    @property
    def des(self):
        return self.gas.des

    @property
    def gas(self):
        """Return the GAS issuing this order."""
        return self.pact.gas
    
    @property
    def supplier(self):
        """Return the supplier this order is placed against."""
        return self.pact.supplier
    
    @property
    def suppliers(self):
        return Supplier.objects.filter(pk=self.supplier.pk)
    
    @property
    def orderable_products(self):
        return self.orderable_product_set.all()
    #ERROR: An unexpected error occurred while tokenizing input
    #The following traceback may be corrupted or invalid
    #The error message is: ('EOF in multi-line statement', (390, 0))

    @property
    def ordered_gasmembers(self):
        from django.db.models import Count, Sum
        #Cannot resolve keyword 'order' into field. Choices are: id, is_confirmed, note, ordered_amount, ordered_price, ordered_product, purchaser, withdrawn_amount
        #return self.ordered_products.extra(select = {'sum_amount': 'SUM(ordered_amount * ordered_price)'}, ).values('ordered_product__order', 'purchaser', 'sum_amount').annotate( tot_product = Count('ordered_product'), sum_qta = Sum('ordered_amount'), sum_price = Sum('ordered_price') ).order_by('purchaser').filter( is_confirmed = True)
#        return self.ordered_products.values('ordered_product__order', 'purchaser').annotate( tot_product = Count('ordered_product'), sum_qta = Sum('ordered_amount'), sum_price = Sum('ordered_price') ).order_by('purchaser').filter( is_confirmed = True)
        #GASMemberOrder.objects.raw("SELECT ... from <GASMemberOrder_table_name> where ...")
        #self.line_items.extra(select=("lineprice": "orderline__price*orderline__qty")).aggregate(Sum('lineprice'))

        #return self.ordered_products.annotate('purchaser', tot_product = Count('ordered_product'), sum_qta = Sum('ordered_amount'), sum_price = Sum('ordered_price') ).order_by('purchaser').filter( is_confirmed = True)

        #return self.ordered_products.extra(select = {'sum_amount': 'SUM(ordered_amount * ordered_price)'}, ).values('ordered_product__order', 'purchaser', 'sum_amount').annotate( tot_product = Count('ordered_product'), sum_qta = Sum('ordered_amount'), sum_price = Sum('ordered_price') ).order_by('purchaser').filter( is_confirmed = True)

        #Do not use string formatting on raw queries!
        return GASMember.objects.raw("\
SELECT tmp.id AS id,  \
( SELECT SUM(gmo.ordered_price*gmo.ordered_amount) FROM \
gas_gasmemberorder AS gmo \
INNER JOIN gas_gassupplierorderproduct AS gsop \
ON gmo.ordered_product_id = gsop.id \
WHERE gsop.order_id = %s AND gmo.purchaser_id = tmp.id \
) AS sum_amount FROM gas_gasmember as tmp \
WHERE tmp.id IN ( SELECT gmo2.purchaser_id FROM gas_gasmemberorder as gmo2 \
INNER JOIN gas_gassupplierorderproduct AS gsop2 \
ON gmo2.ordered_product_id = gsop2.id \
WHERE gsop2.order_id = %s ) \
", [self.pk, self.pk])

#SELECT tmp2.* , bp.surname, bp.name from (  \
#SELECT tmp.id AS id, tmp.person_id AS pb_id,  \
#) as tmp2 inner join base_person as bp on bp.id = tmp2.pb_id \
#order by tmp2.id desc, bp.surname, bp.name \

        #<RawQuerySet: 'SELECT * from GASMemberOrder'>

    @property
    def ordered_gasmembers_sql(self):
        from django.db import connection, transaction
        cursor = connection.cursor()
        #Using psycopg2:
        #import psycopg2.extras
        #cursor = connection.cursor(cursor_factory=psycopg2.extras.DictCursor)
        #Using Mysqldb:
        #import MySQLdb.cursors
        #cursor = connection.cursor(MySQLdb.DictCursor)
        #cursor.execute() will then return a dictionary like object. 

#TODO: Verify
#mysql    : SELECT a,b,c,d,e                 FROM table GROUP BY a
#postgres : SELECT DISTINCT ON (a) a,b,c,d,e FROM table ORDER BY a,b,c
        # Data retrieval operation - no commit required
        # p.name || ' ' || p.surname --> POSTGRES

#TODO: Verify
#mysql    : CAST(-125.823123123 AS DECIMAL(30, 2)) AS account_amounted
#postgres : to_char(-125.8, '9999.99') AS account_amounted

#        cursor.execute("SELECT \
#tmp.order_id AS order_id\
#, tmp.purchaser_id AS purchaser_id \
#, tmp.sum_amount AS sum_amount \
#, tmp.sum_price AS sum_price \
#, tmp.tot_product AS tot_product \
#, tmp.sum_qta AS sum_qta \
#, (SELECT p.surname FROM gas_gasmember as gm INNER JOIN base_person AS p ON gm.person_id = p.id WHERE gm.id = tmp.purchaser_id ) AS gasmember \
#, CAST(0 AS DECIMAL(30, 2)) AS account_amounted \
#FROM (SELECT gmo.purchaser_id AS purchaser_id \
#, gsop.order_id AS order_id \
#, SUM(gmo.ordered_amount * gsop.order_price) AS sum_amount \
#, SUM(gmo.ordered_price) AS sum_price \
#, COUNT(gmo.ordered_product_id) AS tot_product \
#, SUM(gmo.ordered_amount) AS sum_qta \
#FROM gas_gasmemberorder AS gmo \
#INNER JOIN gas_gassupplierorderproduct AS gsop \
#ON gmo.ordered_product_id = gsop.id \
#WHERE order_id = %s \
#GROUP BY gmo.purchaser_id, gsop.order_id \
#) AS tmp", [self.pk])

        cursor.execute("SELECT id AS purchaser_id,  \
( SELECT SUM(gmo.ordered_price*gmo.ordered_amount) FROM \
gas_gasmemberorder AS gmo \
INNER JOIN gas_gassupplierorderproduct AS gsop \
ON gmo.ordered_product_id = gsop.id \
WHERE order_id = %s \
) AS sum_amount", [self.pk])



        #TODO: Add new field account_amounted
        #Field are retrieve from the Accounting system



        #row = cursor.fetchall()
        #>>> cursor.fetchall()    ((5L, None), (6L, None))
        #write custom SQL queries wich would return dicts instead of tuples
        #row = dictfetchall(cursor)  --> Update Django??? Not Available
        #row = cursor.dictfetchall() 
        #>>> dictfetchall(cursor) [{'parent_id': None, 'id': 5L}, {'parent_id': None, 'id': 6L}]
        desc = cursor.description 
        row = [
            dict(zip([col[0] for col in desc], row))
            for row in cursor.fetchall()
        ]
#{'purchaser': 7L, 'sum_amount': Decimal('98.040000'), 'porder': 10L, 'sum_qta': Decimal('5.00'), 'tot_product': 5L, 'sum_price': Decimal('98.0400')}
#{'purchaser': 11L, 'sum_amount': Decimal('54.840000'), 'porder': 10L, 'sum_qta': Decimal('2.00'), 'tot_product': 2L, 'sum_price': Decimal('54.8400')}

        return row

    @property
    def ordered_products(self):
        return GASMemberOrder.objects.filter(ordered_product__in=self.orderable_products)

    @property
    def stocks(self):
        from gasistafelice.supplier.models import SupplierStock
        stocks_pk=map(lambda x: x[0], self.gasstock_set.values_list('stock'))
        return SupplierStock.objects.filter(pk__in=stocks_pk)

    @property
    def gasstocks(self):
        return self.gasstock_set.all()

    @property
    def gas(self):
        return self.pact.gas

    @property
    def gasmembers(self):
        return self.gas.gasmembers

    @property
    def orders(self):
        return GASSupplierOrder.objects.filter(pk=self.pk)

    @property
    def order(self):
        return self

    @property
    def purchasers(self):
        """
        The set of GAS members participating to this supplier order.
        """
        # FIXME: for consistency, the return value should be a ``QuerySet``
        purchasers = set([order.purchaser for order in self.member_orders])
        return purchasers
    
    @property
    def member_orders(self):
        """
        The queryset of GAS members' orders issued against this supplier order.
        """
        member_orders = GASMemberOrder.objects.filter(ordered_product__order=self)
        return member_orders
    
    @property
    def total_amount(self):
        """
        The total expense for this order, as resulting from the invoice. 
        """
        amount = 0 
        for order_product in self.orderable_products:
            price = order_product.delivered_price
            quantity = order_product.delivered_amount
            amount += price * quantity
        return amount    
    
    @property
    def tot_price(self):
        tot = 0
        for gmo in self.ordered_products:
            tot += gmo.tot_price
        return tot

    @property
    def tot_amount(self):
        tot = 0
        #for gmo in self.ordered_products:
        #    tot += gmo.tot_amount
        if self.ordered_products:
            from django.db.models import Count, Sum
            qry = self.ordered_products.values('purchaser').annotate(sum_qta = Sum('ordered_amount')).order_by('purchaser').filter( is_confirmed = True)
            #tot = self.ordered_products.annotate('purchaser').count()
            #tot = len(self.ordered_products.annotate('purchaser'))
            for agg_gmo in qry:
                tot += agg_gmo.sum_qta
        return tot

    @property
    def tot_gasmembers(self):
        tot = 0
        #for gmo in self.ordered_products:
        #    tot += gmo.tot_amount
        if self.ordered_products:
            from django.db.models import Count, Sum
            qry = self.ordered_products.values('purchaser').annotate(sum_qta = Sum('ordered_amount')).order_by('purchaser').filter( is_confirmed = True)
            #tot = self.ordered_products.annotate('purchaser').count()
            #tot = len(self.ordered_products.annotate('purchaser'))
            tot = qry.count()
        return tot

    @property
    def tot_curtail(self):
        tot = 0
        accounted_amounts = self.gas.accounting.accounted_amount_by_gas_member(self)
        for member in accounted_amounts:
            tot += (member.accounted_amount or 0)
        return tot

    @property
    def payment(self):
        yet_payed, descr =self.gas.accounting.get_supplier_order_data(self)
        return yet_payed

    @property
    def payment_urn(self):
        #mvt_urn = 'order/%s' % self.pk
        mvt_urn = self.urn
        return mvt_urn

    def control_economic_state(self):
        #1/3 control invoice receipt
        if not self.invoice_amount:
            #log.debug("KAPPAO invoice_amount %s " % self.pk)
            return
        #2/3 control members curtails
        qs = self.ordered_gasmembers
        accounted_amounts = self.gas.accounting.accounted_amount_by_gas_member(self)
        for item in qs:
            pass_member = False
            for member in accounted_amounts:
                if member.pk == item.pk:
                    pass_member = True
                    break
            if not pass_member:
                #log.debug("KAPPAO member(%s) %s " % (item, self.pk))
                return
        #3/3 control accounting payment
        tx = self.gas.accounting.get_supplier_order_transaction(self)
        if tx:
            #change state to STATUS_ARCHIVED
            #log.debug("GOTO STATUS_ARCHIVED %s " % self.pk)
            t_name = TRANSITION_ARCHIVE
        else:
            #change state to STATUS_UNPAID
            #log.debug("GOTO STATUS_UNPAID %s " % self.pk)
            t_name = TRANSITION_UNPAID

        # Act as superuser
        user = User.objects.get(username=settings.INIT_OPTIONS['su_username'])
        log.debug("doing trans: %s ,  current_state = %s" % (t_name, self.current_state))
        t = Transition.objects.get(name__iexact=t_name, workflow=self.workflow)

        log.debug("transitions %s. datetime_end is %s" % (get_allowed_transitions(self, user), self.datetime_end))
        if t in get_allowed_transitions(self, user):
            log.debug("Do %s transition. datetime_end is %s" % (t, self.datetime_end))
            self.do_transition(t, user)


    @property
    def insolutes(self):
        orders = GASSupplierOrder.objects.closed().filter(pact=self.pact) | \
            GASSupplierOrder.objects.unpaid().filter(pact=self.pact)
#        orders = None
#        orders |= GASSupplierOrder.objects.closed().filter(pact=self.pact)
#        orders |= GASSupplierOrder.objects.unpaid().filter(pact=self.pact)
        return orders

    def save(self, *args, **kw):
        created = False

        if not self.pk:
            created = True
            if self.gas.config.use_withdrawal_place:

                # Create default withdrawal
                if self.datetime_end and not self.withdrawal:

                    #TODO: check gasconfig for weekday
                    w = Withdrawal(
                            date=self.datetime_end + timedelta(7), 
                            place=self.gas.config.withdrawal_place
                    )
                    w.save()
                    self.withdrawal = w

        super(GASSupplierOrder, self).save(*args, **kw)

        #KO: 20111212 02:00 prepare reccurent plan for order. 
        # becasue Do not create gasstock if order state is prepared
        if created:
            self.set_default_gasstock_set()

    #-------------- Authorization API ---------------#
    
    # Table-level CREATE permission    
    @classmethod
    def can_create(cls, user, context):
        """Who can create a supplier order?

        In general:
            * GAS administrators
            * Referrers for the pact the order is placed against
        Cannot create order if resource related gas have no supplier_referrers.

        In depth we have to switch among multiple possible contexts

        If we are checking for a "unusual key" (not in ctx_keys_to_check),
        just return False, do not raise an exception.
        """

        allowed_users = User.objects.none()
        ctx_keys_to_check = set(('pact', 'gas', 'site', 'supplier'))
        ctx_keys = context.keys()

        if len(ctx_keys) > 1:
            raise WrongPermissionCheck('CREATE [only one key supported for context]', cls, context)

        k = ctx_keys[0]

        if k not in ctx_keys_to_check:
            # No user is allowed, just return False
            # (user is not in User empty querySet)
            # Do not raise an exception
            pass

        # Switch among possible different contexts

        elif k == 'pact':
            # pact context
            pact = context[k]
            if pact.gas.supplier_referrers.count():
                allowed_users = pact.gas.tech_referrers | pact.gas.supplier_referrers

        elif k == 'gas':
            # gas context
            gas = context[k]
            if gas.pacts.count() and gas.supplier_referrers.count():
                allowed_users = gas.tech_referrers | gas.supplier_referrers

        elif k == 'site':
            # des context
            des = context[k]
            if des.pacts.count():
                allowed_users = des.gas_tech_referrers | des.gas_supplier_referrers

        elif k == 'supplier':
            # supplier context
            # Every GAS REFERRER SUPPLIER or GAS REFERRER TECH of a GAS 
            # who has a GASSupplierSolidalPact with this Supplier
            supplier = context[k]
            for pact in supplier.pacts:
                allowed_users |= pact.gas.supplier_referrers | pact.gas.tech_referrers

        return user in allowed_users
 
    # Row-level EDIT permission
    def can_edit(self, user, context):
        # Who can edit details of a supplier order in a GAS ?
        # * order referrers (if any)
        # * referrers for the pact the order is placed against
        # * GAS administrators
        allowed_users = self.referrers | self.gas.tech_referrers | self.gas.supplier_referrers
        return user in allowed_users 
    
    # Row-level DELETE permission
    def can_delete(self, user, context):
        # Who can edit details of a supplier order in a GAS ?
        # * order referrers (if any)
        # * referrers for the pact the order is placed against
        # * GAS administrators  
        allowed_users = self.referrers | self.gas.tech_referrers | self.pact.gas_supplier_referrers
        return user in allowed_users 
    
    #-----------------------------------------------#

    display_fields = (
        display.Resource(name="gas", verbose_name=_("GAS")),
        display.Resource(name="supplier", verbose_name=_("Supplier")),
        models.CharField(max_length=32, name="current_state", verbose_name=_("Current state")),
        datetime_start, datetime_end, order_minimum_amount, 
        delivery, display.Resource(name="referrer_person", verbose_name=_("Referrer")),
        withdrawal, display.Resource(name="withdrawal_referrer_person", verbose_name=_("Withdrawal referrer")),
    )

#-------------------------------------------------------------------------------
class GASSupplierOrderProduct(models.Model, PermissionResource):
    """A Product (actually, a GASSupplierStock) available to GAS Members in the context of a given GASSupplierOrder.
    See `here <http://www.jagom.org/trac/REESGas/wiki/BozzaVocabolario#ListinoFornitoreGasista>`__  for details (ITA only).

    """

    order = models.ForeignKey(GASSupplierOrder, related_name="orderable_product_set",verbose_name=_('order'))
    gasstock = models.ForeignKey(GASSupplierStock, related_name="orderable_product_set",verbose_name=_('gas stock'))
    # how many units of Product a GAS Member can request during this GASSupplierOrder
    # useful for Products with a low availability
    maximum_amount = PrettyDecimalField(null=True, blank=True, verbose_name = _('maximum amount'),
                        max_digits=8, decimal_places=2
    )
    # the price of the Product at the time the GASSupplierOrder was created
    initial_price = CurrencyField(verbose_name=_('initial price'))
    # the price of the Product at the time the GASSupplierOrder was sent to the Supplier
    order_price = CurrencyField(verbose_name=_('order price'))
    # the actual price of the Product (as resulting from the invoice)
    delivered_price = CurrencyField(null=True, blank=True,verbose_name=_('delivered price'))
    # how many items were actually delivered by the Supplier 
    delivered_amount = PrettyDecimalField(null=True, blank=True, verbose_name = _('delivered amount'),
                        max_digits=8, decimal_places=2
    )

    history = HistoricalRecords()
    
    class Meta:
        verbose_name = _('gas supplier order product')
        verbose_name_plural = _('gas supplier order products')
        app_label = 'gas'

    def __unicode__(self):
        rv = _('%(gasstock)s of order %(order)s') % { 'gasstock' : self.gasstock, 'order' : self.order}
        if settings.DEBUG:
            rv += " [%s]" % self.pk
        return rv

    @property
    def has_changed(self):
        return self.initial_price != self.order_price

    # how many items of this kind were ordered (globally by the GAS)
    @property
    def tot_amount(self):
        # grab all GASMemberOrders related to this product and issued by members of the right GAS
        gmo_list = self.gasmember_order_set.values('ordered_amount')
        amount = 0 
        for gmo in gmo_list:         
            amount += gmo['ordered_amount']
        return amount 

    @property
    def tot_gasmembers(self):
        return self.gasmember_order_set.count()

    @property
    def unconfirmed_orders(self):
        return self.gasmember_order_set.filter(is_confirmed=False).count()

    @property
    def tot_price(self):
        """Grab all GASMemberOrders related to this orderable product"""

        #INFO: i.e. if you want to optimize this method you could write:
        #INFO: self.gasmember_order_set.values('ordered_price', 'ordered_amount')
        #INFO: and compute tot_price in here.
        
        gmo_list = self.gasmember_order_set.all()
        tot = 0 
        for gmo in gmo_list:
            tot += gmo.tot_price
        return tot 

    @property
    def pact(self):
        return self.order.pact

    @property
    def gas(self):
        return self.order.pact.gas

    @property
    def supplier(self):
        return self.order.supplier

    @property
    def product(self):
        return self.gasstock.product

    @property
    def stock(self):
        return self.gasstock.stock
    
    def save(self, *args, **kw):
        """Sef default initial price"""
        if not self.pk:
            self.initial_price = self.order_price
        if self.delivered_price is None:
            self.delivered_price = self.order_price

        super(GASSupplierOrderProduct, self).save(*args, **kw)

        # CASCADING set until GASMemberOrder
        if self.has_changed_price:
            log.debug('Price has changed for gsop (%s) [ %s--> %s]' %  (self.pk, self.order_price))
            for gmo in self.gasmember_order_set:
                #gmo.order_price = self.order_price
                gmo.note = _("Price changed on %(date)s") % { 'date' : datetime.now() }
                gmo.save()


    @property
    def has_changed_price(self):
        try:
            gsop = GASSupplierOrderProduct.objects.get(pk=self.pk)
            if not gsop is None:
                return bool(self.order_price != gsop.order_price)
            else:
                return False
        except GASSupplierOrderProduct.DoesNotExist:
            return False

    #-------------- Authorization API ---------------#

    # Table-level CREATE permission    
    @classmethod
    def can_create(cls, user, context):
        # Who can add a new product to a supplier order in a GAS ?
        # * order referrers (if any)
        # * referrers for the pact the order is placed against
        # * GAS administrators        
        try:
            order = context['order']
            allowed_users = order.referrers | order.gas.tech_referrers | order.pact.gas_supplier_referrers
            return user in allowed_users
        except KeyError:
            raise WrongPermissionCheck('CREATE', cls, context)

    # Row-level EDIT permission
    def can_edit(self, user, context):
        # Who can edit details of product associated with a supplier order in a GAS ?
        # * order referrers (if any)
        # * referrers for the pact the order is placed against
        # * GAS administrators        
        allowed_users = self.order.referrers | self.gas.tech_referrers | self.pact.gas_supplier_referrers
        return user in allowed_users
    
    # Row-level DELETE permission
    def can_delete(self, user, context):
        # Who can delete a product associated with a supplier order in a GAS ?
        # * order referrers (if any)
        # * referrers for the pact the order is placed against
        # * GAS administrators    
        allowed_users = self.order.referrers | self.gas.tech_referrers | self.pact.gas_supplier_referrers        
        return user in allowed_users 


class GASMemberOrder(models.Model, PermissionResource):

    """An order made by a GAS member in the context of a given GASSupplierOrder.

    See `here http://www.jagom.org/trac/REESGas/wiki/BozzaVocabolario#OrdineGasista`__  for details (ITA only).

    """

    purchaser = models.ForeignKey(GASMember, related_name="gasmember_order_set", null=False, blank=False,verbose_name=_('purchaser'))
    ordered_product = models.ForeignKey(GASSupplierOrderProduct, related_name="gasmember_order_set", null=False, blank=False,verbose_name=_('order product'))
    # price of the Product at order time
    ordered_price = CurrencyField(verbose_name=_('ordered price'))
    # how many Product units were ordered by the GAS member
    ordered_amount = PrettyDecimalField(null=False, blank=False, verbose_name = _('order amount'),
                        max_digits=6, decimal_places=2
    )
    # how many Product units were withdrawn by the GAS member 
    withdrawn_amount = PrettyDecimalField(null=True, blank=True, verbose_name = _('widthdrawn amount'),
                        max_digits=6, decimal_places=2
    )
    # gasmember order have to be confirmed if GAS configuration allowed it
    is_confirmed = models.BooleanField(default=False,verbose_name=_('confirmed'))

    note = models.CharField(max_length=64, verbose_name=_('product note'), null=True, blank=True, help_text=_("GAS member can write some short message about this product for the producer"))

    history = HistoricalRecords()

    class Meta:
        app_label = 'gas'
        verbose_name = _('GAS member order')
        verbose_name_plural = _('GAS member orders')
        unique_together = (('ordered_product', 'purchaser'),)

    def __unicode__(self):
        return u"Ordered product %(product)s by GAS member %(gm)s" % { 'product' : self.product, 'gm': self.gasmember }
    
    def confirm(self):
        self.is_confirmed = True

    @property
    def has_changed(self):
        return self.ordered_product.order_price != self.ordered_price

    @property
    def tot_price(self):
        """Ordered price per ordered amount for this ordered product"""
        #FIXME: we have to use self.ordered_price instead of self.ordered_product.order_price?
        return self.ordered_product.order_price * self.ordered_amount

    @property
    def gasmember(self):
        return self.purchaser

    @property
    def product(self):
        return self.ordered_product.product

    @property
    def supplier(self):
        return self.ordered_product.supplier

    @property
    def email(self):
        return self.purchaser.email

    @property
    def order(self):
        """GASSupplierOrder this GASMemberOrder belongs to."""

        return self.ordered_product.order

    @property
    def gas(self):
        """Which GAS this order belongs"""
        return self.purchaser.gas

    # Workflow management

    @property
    def workflow(self):
        return get_workflow(self)

    @workflow.setter
    def workflow(self, value=None):
        raise AttributeError(_("Workflow for specific GASMemberOrder is not allowed. Just provide a default order workflow for your GAS"))

    def forward(self, user):
        """Apply default transition"""
        state = get_state(self)
        transition = DefaultTransition.objects.get(workflow=self.workflow, state=state).transition
        do_transition(self, transition, user)
 
    def save(self, *args, **kw):

        # Delete a GAS Member order if amount == 0
        if not self.ordered_amount:
            return self.delete()

        #Duplicate Entry. Retrieve data from database
        if not self.pk:
            YetExist = GASMemberOrder.objects.filter(ordered_product=self.ordered_product, purchaser=self.purchaser)
            if YetExist and YetExist.count() > 0:
                self.pk = YetExist[0].pk

        if not self.workflow:
            # Set default workflow
            w = self.gas.config.default_workflow_gasmember_order
            set_workflow(self, w)

        #If the GAS's member do not have to confirm is order auto set the flag
        if not self.purchaser.gas.config.gasmember_auto_confirm_order:
            self.is_confirmed = True

        return super(GASMemberOrder, self).save(*args, **kw)
    
    #-------------- Authorization API ---------------#
    
    # Table-level CREATE permission    
    @classmethod
    def can_create(cls, user, context):
        # Who can issue an order *to* a GAS ?
        # *  members of that GAS
        try:
            order = context['order']
            allowed_users = order.gas.members
            return user in allowed_users
        except KeyError:
            raise WrongPermissionCheck('CREATE', cls, context)

    # Row-level EDIT permission
    def can_edit(self, user, context):
        # Who can modify an order placed by a GAS member ?
        # * the member itself (of course)
        # * order referrers (if any)
        # * referrers for the pact the order is placed against 
        # * GAS administrators                
        allowed_users = self.purchaser | self.order.referrers | self.gas.tech_referrers | self.pact.gas_supplier_referrers
        return user in allowed_users
    
    # Row-level DELETE permission
    def can_delete(self, user, context):
        # Who can delete an order placed by a GAS member ?
        # * the member itself (of course)
        # * order referrers (if any)
        # * referrers for the pact the order is placed against 
        # * GAS administrators                
        allowed_users = self.purchaser | self.order.referrers | self.gas.tech_referrers | self.pact.gas_supplier_referrers
        return user in allowed_users
    
    #---------------------------------------------------#
     

class Appointment(models.Model):
    """
    A base, abstract model class meant to factor out fields common to appointment-like models
    (i.e.  meetings, events, ..)
    """
    
    objects = AppointmentManager()
    
    class Meta:
        abstract = True

#-------------------------------------------------------------------------------#
# Model Archive API
        
    def is_active(self):
        """
        Return `True` if the Appointment is to be considered as 'active'; `False` otherwise.
        """
        return self in Appointment.objects.future()
    
    def is_archived(self):
        """
        Return `True` if the Appointment is to be considered as 'archived'; `False` otherwise.
        """
        return not self.is_active()
    
#-------------------------------------------------------------------------------#    


class Delivery(Appointment, PermissionResource):

    """
    A delivery appointment, i.e. an event where one or more Suppliers deliver goods 
    associated with SupplierOrders issued by a given GAS (or Retina of GAS).  
    """
    
    place = models.ForeignKey(Place, related_name="delivery_set", help_text=_("where the order will be delivered by supplier"),verbose_name=_('place'))
    date = models.DateTimeField(help_text=_("when the order will be delivered by supplier"),verbose_name=_('date'))    

    history = HistoricalRecords()

    class Meta:
        app_label = 'gas'
        verbose_name = _('delivery')
        verbose_name_plural = _('deliveries')
        
    def __unicode__(self):
        return "%(date)s at %(place)s" % {'date':self.date, 'place':self.place}
    
    @property
    def gas_list(self):
        """
        Return a QuerySet containing all GAS sharing this delivery appointment. 
        """
        pacts = GASSupplierSolidalPact.objects.filter(order_set__in=self.order_set.all())
        return GAS.objects.filter(pact_set__in = pacts)
    
    #-------------------------------------------------------------------------------#   
    # Referrers API
        
    @property
    def referrers(self):
        """
        Return all users being referrers for this delivery appointment.
        """
        # retrieve 'delivery referrer' parametric role for this order
        pr = ParamRole.get_role(GAS_REFERRER_DELIVERY, delivery=self)
        # retrieve all Users having this role
        return pr.get_users()       
 
    @property
    def persons(self):
        return self.referrers_people

    
#-------------------------------------------------------------------------------#

    #-------------- Authorization API ---------------#
    
    # COMMENT-fero: now we do not use authoriazion API on this model.
    # we have to make some consideration for deliveries shared on more than one order
    
    # Table-level CREATE permission    
    @classmethod
    def can_create(cls, user, context):
        # TODO: REVIEW NEEDED see below (Withdrawal.can_create)
        # Who can schedule a new delivery appointment for a GAS ?
        # * pact referrers (all)
        # * order referrers (all, if any)
        # * GAS administrators       

        # TODO: order referres: ticket www.jagom.org/trac/reesgas/ticket/185
        # add.. "evryone is referrer for one active order in GAS

        allowed_users = User.objects.none()
        try:
            # gas context
            gas = context['gas']
            allowed_users = gas.supplier_referrers | gas.tech_referrers
        except KeyError:
            try:
                # TODO: ticket www.jagom.org/trac/reesgas/ticket/185
                # order context
                order = context['order']
                raise NotImplementedError("can_create withdrawal in order")
                allowed_users = order.referrers | order.gas.supplier_referrers | order.gas.tech_referrers
            except KeyError:
                raise WrongPermissionCheck('CREATE', cls, context)

        return user in allowed_users
 
    # Row-level EDIT permission
    def can_edit(self, user, context):
        # TODO: REVIEW NEEDED see above (can_create)
        # Who can modify a delivery appointment ?
        # (remember that they can be shared among orders and GASs)
        # 1) If only one supplier order is currently associated with this appointment:
        #     * order referrers (if any) 
        #     * referrers for the pact that order is placed against
        #     * GAS administrators
        # 2) If more than one order is currently associated with this appointment,
        #    but they belogns to the same GAS:
        #     * GAS administrators            
        # 3) ELSE:
        #     * DES administrators

        allowed_users = User.objects.none()
        associated_orders = self.order_set.all()  
        if len(associated_orders) == 1:
            order = associated_orders[0] 
            allowed_users = order.referrers | order.gas.tech_referrers | order.pact.gas_supplier_referrers                    
        elif len(self.gas_list) == 1:
            gas = self.gas_list[0]
            allowed_users = gas.tech_referrers
            
        return user in allowed_users
    
    # Row-level DELETE permission
    def can_delete(self, user, context):
        # TODO: REVIEW NEEDED see above (can_create)
        # Who can delete a delivery appointment ?
        # (remember that they can be shared among orders and GASs)
        # 1) If only one supplier order is currently associated with this appointment:
        #     * order referrers (if any) 
        #     * referrers for the pact that order is placed against
        #     * GAS administrators
        # 2) If more than one order is currently associated with this appointment,
        #    but they belogns to the same GAS:
        #     * GAS administrators            
        # 3) ELSE:
        #     * DES administrators
        allowed_users = User.objects.none()
        associated_orders = self.order_set.all()  
        if len(associated_orders) == 1:
            order = associated_orders[0] 
            allowed_users = order.referrers | order.gas.tech_referrers | order.pact.gas_supplier_referrers                    
        elif len(self.gas_list) == 1:
            gas = self.gas_list[0]
            allowed_users = gas.tech_referrers
            
        return user in allowed_users
    
        
    #---------------------------------------------------#
     
    

class Withdrawal(Appointment, PermissionResource):
    """
    A wihtdrawal appointment, i.e. an event where a GAS (or Retina of GAS) distribute 
    to their GASMembers goods they ordered issuing GASMemberOrders to the GAS/Retina.  
    """
    
    place = models.ForeignKey(Place, related_name="withdrawal_set", help_text=_("where the order will be withdrawn by GAS members"))
    #TODO FIXME AFTER 6th of september: 
    # * date should be Date field
    # * start_time and end_time (with no defaults) must be managed in forms
    date = models.DateTimeField(help_text=_("when the order will be withdrawn by GAS members"))

    # a Withdrawal appointment usually span a time interval
    start_time = models.TimeField(default="18:00", help_text=_("when the withdrawal will start"))
    end_time = models.TimeField(default="22:00", help_text=_("when the withdrawal will end"))

    history = HistoricalRecords()

    class Meta:
        app_label = 'gas'
        verbose_name = _('wihtdrawal')
        verbose_name_plural = _('wihtdrawals')
    
    def __unicode__(self):
        return "At %(place)s on %(date)s from %(start_time)s to %(end_time)s" % {
                    'start_time':self.start_time.strftime("%H:%M"), 
                    'end_time':self.end_time.strftime("%H:%M"), 
                    'date':self.date.strftime("%d-%m-%Y"), 
                    'place':self.place
        }
    
    
    @property
    def gas_list(self):
        """
        Return a QuerySet containing all GAS sharing this withdrawal appointment. 

        """
        pacts = GASSupplierSolidalPact.objects.filter(order_set__in=self.order_set.all())
        return GAS.objects.filter(pact_set__in = pacts)

    #-------------------------------------------------------------------------------#   
    # Referrers API
        
    @property
    def referrers(self):
        """
        Return all users being referrers for this wihtdrawal appointment.
        """
        # retrieve 'wihtdrawal referrer' parametric role for this order
        pr = ParamRole.get_role(GAS_REFERRER_WITHDRAWAL, withdrawal=self)
        # retrieve all Users having this role
        return pr.get_users()       

    @property
    def persons(self):
        return self.referrers_people

         
#-------------------------------------------------------------------------------#


    #-------------- Authorization API ---------------#

    # COMMENT-fero: now we do not use authoriazion API on this model.
    # we have to make some consideration for withdrawals shared on more than one order
    
    # Table-level CREATE permission    
    @classmethod
    def can_create(cls, user, context):
        # Who can schedule a new withdrawal appointment for a GAS ?
        # * pact referrers (all)
        # * GAS administrators       

        # TODO: order referres: ticket www.jagom.org/trac/reesgas/ticket/185
        # add.. "evryone is referrer for one active order in GAS

        allowed_users = User.objects.none()
        try:
            # gas context
            gas = context['gas']
            allowed_users = gas.supplier_referrers | gas.tech_referrers
        except KeyError:
            try:
                # TODO: ticket www.jagom.org/trac/reesgas/ticket/185
                # order context
                order = context['order']
                raise NotImplementedError("can_create withdrawal in order")
                allowed_users = order.referrers | order.gas.supplier_referrers | order.gas.tech_referrers
            except KeyError:
                raise WrongPermissionCheck('CREATE', cls, context)

        return user in allowed_users

    # Row-level EDIT permission
    def can_edit(self, user, context):
        # TODO: REVIEW NEEDED see above (can_create)
        # Who can modify a withdrawal appointment ?
        # (remember that they can be shared among orders and GASs)
        # 1) If only one supplier order is currently associated with this appointment:
        #     * order referrers (if any) 
        #     * referrers for the pact that order is placed against
        #     * GAS administrators
        # 2) If more than one order is currently associated with this appointment,
        #    but they belogns to the same GAS:
        #     * GAS administrators            
        # 3) ELSE:
        #     * DES administrators
        allowed_users = User.objects.none()
        associated_orders = self.order_set.all()  
        if len(associated_orders) == 1:
            order = associated_orders[0] 
            allowed_users = order.referrers | order.gas.tech_referrers | order.pact.gas_supplier_referrers                    
        elif len(self.gas_list) == 1:
            gas = self.gas_list[0]
            allowed_users = gas.tech_referrers
            
        return user in allowed_users
    
    # Row-level DELETE permission
    def can_delete(self, user, context):
        # TODO: REVIEW NEEDED see above (can_create)
        # Who can delete a withdrawal appointment ?
        # (remember that they can be shared among orders and GASs)
        # 1) If only one supplier order is currently associated with this appointment:
        #     * order referrers (if any) 
        #     * referrers for the pact that order is placed against
        #     * GAS administrators
        # 2) If more than one order is currently associated with this appointment,
        #    but they belogns to the same GAS:
        #     * GAS administrators            
        # 3) ELSE:
        #     * DES administrators
        allowed_users = User.objects.none()
        associated_orders = self.order_set.all()  
        if len(associated_orders) == 1:
            order = associated_orders[0] 
            allowed_users = order.referrers | order.gas.tech_referrers | order.pact.gas_supplier_referrers                    
        elif len(self.gas_list) == 1:
            gas = self.gas_list[0]
            allowed_users = gas.tech_referrers
            
        return user in allowed_users
            
    #---------------------------------------------------#
