from django.utils.translation import ugettext, ugettext_lazy as _

NOBODY = 'NOBODY'
SUPPLIER_REFERRER = 'SUPPLIER_REFERRER'
GAS_MEMBER = 'GAS_MEMBER'
GAS_SUPPLIER_REFERRER = 'GAS_SUPPLIER_REFERRER'
GAS_ORDER_REFERRER = 'GAS_ORDER_REFERRER'
GAS_WITHDRAW_REFERRER = 'GAS_WITHDRAW_REFERRER'
GAS_DELIVERY_REFERRER = 'GAS_DELIVERY_REFERRER'
GAS_CASH_REFERRER = 'GAS_CASH_REFERRER'
GAS_TECH_REFERRER = 'GAS_TECH_REFERRER'


ROLES_LIST = [
(NOBODY, _('Nobody')),
(SUPPLIER_REFERRER, _('Supplier referrer')),
(GAS_MEMBER, _('GAS member')),
(GAS_SUPPLIER_REFERRER, _('GAS supplier referrer')),
(GAS_ORDER_REFERRER, _('GAS order referrer')),
(GAS_WITHDRAW_REFERRER, _('GAS withdrawal referrer')),
(GAS_DELIVERY_REFERRER, _('GAS delivery referrer')),
(GAS_CASH_REFERRER, _('GAS cash referrer')),
(GAS_TECH_REFERRER, _('GAS technical referrer')),
]

SUPPLIER_FLAVOUR_LIST = [
('COMPANY', _('Company')),
('COOPERATING', _('Cooperating')),
]

MU_CHOICES = [('Km', 'Km')]
ALWAYS_AVAILABLE = 1000000000

CONTACT_CHOICES = [
('PHONE', _('PHONE')),
('EMAIL', _('EMAIL')),
('FAX', _('FAX')),
]
